language: ruby

rbenv:
  - 2.2.0

env:
  - DB=pgsql

services:
  - postgresql
  - elasticsearch

script:
  - bundle exec rake db:drop db:create db:migrate RAILS_ENV=test
  - bundle exec rake

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database courseselect_test;' -U postgres
